Postgres:
 Host: "0.0.0.0"
 Port: 5432
 Login: postgres
 Password: 1234 
 ConnMaxLifeTime: 3
 MaxOpenConn: 10
 MaxIdleConn: 10
GrpcServer:
 Host: localhost
 Port: :50051
 Timeout: 15
 ReadTimeout: 5
 WriteTimeout: 5
 MaxConnectionIdle: 5
 MaxConnectionAge: 5