name: Tests

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 test:
  runs-on: ubuntu-20.04
  steps:
   - uses: actions/checkout@v2 # download code from this repo to runner

   - name: Install Go
     uses: actions/setup-go@v2
     with:
      go-version: 1.19

   - name: Verify dependencies
     run: go mod verify
  
   - name: Build
     run: go build -v ./...

   - name: Run go vet 
     run: go vet ./...

   - name: Install staticcheck
     run: go install honnef.co/go/tools/cmd/staticcheck@latest
   
   - name: Run staticcheck 
     run: staticcheck ./...

   - name: Install golint 
     run: go install golang.org/x/lint/golint@latest

   - name: Run golint 
     run: golint ./...

   - name: Create and start containers
     run: make test

   - name: Run tests
     run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
     
   - name: "Cleaning"
     run: docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -a -q)

   - name: Upload coverage to Codecov
     uses: codecov/codecov-action@v3