name: Tests

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 test:
  runs-on: ubuntu-20.04
  steps:
   - uses: actions/checkout@v2 # download code from this repo to runner
   
   - name: Install Go
     uses: actions/setup-go@v2
     with:
      go-version: 1.19

   - name: Verify dependencies
     run: go mod verify
  
   - name: Build
     run: go build -v ./...

   - name: Run go vet 
     run: go vet ./...

   - name: Install staticcheck
     run: go install honnef.co/go/tools/cmd/staticcheck@latest
   
   - name: Run staticcheck 
     run: staticcheck ./...

   - name: Install golint 
     run: go install golang.org/x/lint/golint@latest

   - name: Run golint 
     run: golint ./...

   - name: Run tests
     run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
     
   - name: Upload coverage to Codecov
     uses: codecov/codecov-action@v3
     with:
#         token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#         files: ./cover.txt
        flags: unit
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
